name: Keepalive Workflows
description: |
  Turns off and then back all workflows on the repository this action is run on
  to ensure that they are not automatically disabled after 60 days of
  inactivity.
author: Emmanuel Frecon <efrecon+github@gmail.com>
branding:
  icon: activity
  color: green

inputs:
  token:
    description: |
      Token with enough privileges (repo:* scope) to perform action state
      operations.
    required: false
    default: "${{ github.token }}"
  options:
    description: |
      Additional options to keepalive script, e.g. -v to print out additional
      verbose information. This is a semi-internal input and should only be used
      for debugging.
    required: false
    default: ""
  timeout:
    description: |
      The number of seconds of inactivity on the default branch before
      generating a commit. The default is 41 days, i.e. just above 2/3 of the
      GitHub inactivity trigger.
    required: false
    default: 3542400
  marker:
    description: |
      The default is to have an empty marker, in which case this action will use
      a hidden file within the workflows directory when it is necessary to
      generate activite on the repository to keep it alive. The name of that
      file is controlled by the environment variable `ACTIVITY_LIVENESS_STORE`.
      You can also pass the name of the workflow instead, e.g. the value of
      `github.workflow`, in which case the marker will be added/updated at the
      end of the workflow that called the action. This requires a GitHub token
      that is able to change workflows, which the default `GITHUB_TOKEN` cannot
      do.
    required: false
    default: ""

runs:
  using: composite
  steps:
    -
      name: Minimal Checkout
      id: checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        fetch-depth: 1
    -
      name: Activity Keeper
      id: activator
      shell: bash
      env:
        ACTIVITY_GHAPI: ${{ github.api_url }}
      run: |
        ${{ github.action_path }}/activity.sh \
          -t '${{ inputs.token }}' \
          -m '${{ inputs.timeout }}' \
          ${{ inputs.options }} \
          -- \
            '${{ inputs.marker }}' \
            '${{ github.repository }}'
