name: Keepalive Workflows
description: |
  Turns off and then back all workflows on the repository this action is run on
  to ensure that they are not automatically disabled after 60 days of
  inactivity.
author: Emmanuel Frecon <efrecon+github@gmail.com>
branding:
  icon: activity
  color: green

inputs:
  token:
    description: |
      Token with enough privileges (repo:* scope) to perform action state
      operations.
    required: false
    default: "${{ github.token }}"
  options:
    description: |
      Additional options to keepalive script, e.g. -v to print out additional
      verbose information. This is a semi-internal input and should only be used
      for debugging.
    required: false
    default: ""
  timeout:
    description: |
      The number of seconds of inactivity on the default branch before
      generating a commit. The default is 41 days, i.e. just above 2/3 of the
      GitHub inactivity trigger.
    required: false
    default: 3542400

runs:
  using: composite
  steps:
    -
      name: Minimal Checkout
      id: checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        fetch-depth: 1
    -
      name: Activity Keeper
      id: activator
      shell: bash
      env:
        ACTIVITY_GHAPI: ${{ github.api_url }}
      run: |
        ${{ github.action_path }}/activity.sh \
          -t '${{ inputs.token }}' \
          -m '${{ inputs.timeout }}' \
          ${{ inputs.options }} \
          -- \
            '${{ github.workflow }}' \
            '${{ github.repository }}'
