name: keepalive

on:
  schedule:
    # Run every sunday at 1:27 UTC
    - cron: '27 1 * * SUN'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: keepalive
        if: github.event_name == 'schedule'
        uses: ./
      - name: force keepalive
        if: github.event_name != 'schedule'
        uses: ./
        with:
          timeout: 0